name: 02 - Workflow Events

on: 
    # push:
    # schedule:
    #     - cron: "*/1 * * * *" //github only allows cron jobs to run every 5 minutes or more
    # pull_request:
    workflow_dispatch:

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: |
                echo "Event name: ${{ github.event_name }}"